<?php
// $Id: webform_submissions_acl.module,v 1.1 2009/10/30 17:49:17 davyvandenbremt Exp $

/**
 * @file
 * Drupal hooks and helper functions.
 *
 * @author Davy Van Den Bremt
 * Modified by: Edouard Poitras <epoitras@layer8.org> on June 27th, 2012 in an attempt
 * to get it working with Drupal 7
 * Thanks to pbosmans (drupal username) for the permissions fix @ http://drupal.org/node/1561834
 * Thanks to Matt B (drupal username) for the module package placement idea @ http://drupal.org/node/1111124
 * Thanks to Zyxtrio (drupal username) for the role based ACL code @ http://drupal.org/node/636612
 */

/**
 * Implementation of hook_menu().
 */
function webform_submissions_acl_menu() {
  $items = array();
  $items['node/%webform_menu/acl'] = array(
    'title' => 'ACL',
    'page callback' => 'webform_submissions_acl_page',
    'page arguments' => array('webform_submissions_acl_page', 1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'webform_submissions_acl.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  $items['node/%webform_menu/acl/delete/%user'] = array(
    'title' => 'ACL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_submissions_acl_delete_confirm_form', 1, 5),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'webform_submissions_acl.pages.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function webform_submissions_acl_admin_paths() {
  $paths = array(
    'node/*/acl' => TRUE,
    'node/*/acl/delete/%user' => TRUE,
  );
  return $paths;
}

/**
 * Implementation of hook_menu_alter().
 */
function webform_submissions_acl_menu_alter(&$callbacks) {
  $callbacks['node/%webform_menu/webform-results']['access callback'] = 'webform_submissions_acl_access';
  $callbacks['node/%webform_menu/webform-results']['access arguments'] = array(1, 'access own webform results');
  $callbacks['node/%webform_menu/webform-results/analysis']['access callback'] = 'webform_submissions_acl_access';
  $callbacks['node/%webform_menu/webform-results/analysis']['access arguments'] = array(1, 'access own webform results');
  $callbacks['node/%webform_menu/webform-results/table']['access callback'] = 'webform_submissions_acl_access';
  $callbacks['node/%webform_menu/webform-results/table']['access arguments'] = array(1, 'access own webform results');
  $callbacks['node/%webform_menu/webform-results/download']['access callback'] = 'webform_submissions_acl_access';
  $callbacks['node/%webform_menu/webform-results/download']['access arguments'] = array(1, 'access own webform results');
  $callbacks['node/%webform_menu/webform-results/submissions']['access callback'] = 'webform_submissions_acl_access';
  $callbacks['node/%webform_menu/webform-results/submissions']['access arguments'] = array(1, 'access own webform results');
  $callbacks['node/%webform_menu/submissions']['access callback'] = 'webform_submissions_acl_access';
  $callbacks['node/%webform_menu/submissions']['access arguments'] = array(1, 'access own webform results');
  $callbacks['node/%webform_menu/submission/%webform_menu_submission']['access callback'] = 'webform_submissions_acl_access';
  $callbacks['node/%webform_menu/submission/%webform_menu_submission']['access arguments'] = array(1, 'access own webform results');
}

/**
 * Menu access callback. Ensure a user both access (permission or acl) and node 'view' permission.
 */
function webform_submissions_acl_access($node, $perm) {
  global $user;
  $node_users = webform_submissions_acl_users_by_node($node->nid, TRUE);
  return node_access('view', $node) && (user_access('access all webform results') || ((user_access($perm) && ($user->uid == $node->uid)) || in_array($user->uid, $node_users)));
}

/**
 * Implementation of hook_theme().
 */
function webform_submissions_acl_theme($existing, $type, $theme, $path) {
  return array(
    'webform_submissions_acl_page' => array(
      'variables' => array(
        'form' => '',
        'node' => NULL,
        'users' => array()
      ),
    ),
  );
}

function webform_submissions_acl_users_by_node($nid, $id_only = FALSE) {
  $users = array();
  $result = db_query("SELECT wsa.uid, u.name FROM {webform_submissions_acl} wsa INNER JOIN {users} u ON u.uid = wsa.uid WHERE wsa.nid = :nid", array(':nid' => $nid));
  foreach ($result as $row) {
    if ($id_only) {
      $users[] = $row->uid;
    }
    else {
      $users[] = $row;
    }
  }
  return $users;
}

function webform_submissions_acl_nodes_by_user($uid, $id_only = FALSE) {
  $nodes = array();
  $result = db_query("SELECT wsa.nid, wsa.title FROM {webform_submissions_acl} wsa INNER JOIN {node} n ON n.nid = wsa.nid WHERE wsa.uid = " . $uid);
  foreach ($result as $row) {
    if ($id_only) {
      $nodes[] = $row->nid;
    }
    else {
      $nodes[] = $row;
    }
  }
  return $nodes;
}

/*function webform_submissions_acl_users_by_role($nid, $rid, $id_only = FALSE) {
  $users = array();
  $result = db_query("SELECT u.uid, u.name, u.status FROM {users} u INNER JOIN {users_roles} ur ON u.uid=ur.uid WHERE ur.rid = %d AND u.status = 1", $rid);
  foreach ($result as $row) {
    if ($id_only) {
      $users[] = $row->uid;
    }
    else {
      $users[] = $row;
    }
  }
  return $users;
} */

function webform_submissions_acl_delete($nid, $uid) {
  db_delete('webform_submissions_acl')->condition('nid', $nid)->condition('uid', $uid)->execute();
}
